export const shirts=[
    {
        name:"one-piece shirt",
        price: 130.00,
        image: "anime.jpg",
        size: ["S", "M", "L", "XL"],
        color: ["Black"],
        category: "Anime",
        arrival:"New Arrival",
    },
    {
        name:"two-piece shirt",
        price: 130.00,
        image: "anime.jpg",
        size: ["S", "M", "L", "XL"],
        color: ["Black"],
        category: "Anime",
        arrival:"New Arrival",
    },
    {
        name:"three-piece shirt",
        price: 130.00,
        image: "anime.jpg",
        size: ["S", "M", "L", "XL"],
        color: ["Black"],
        category: "Anime",
        arrival:"New Arrival",
    },
    {
        name:"four-piece shirt",
        price: 130.00,
        image: "anime.jpg",
        size: ["S", "M", "L", "XL"],
        color: ["White", "Black"],
        category: "Anime",
        arrival:"New Arrival",
    },
    {
        name:"five-piece shirt",
        price: 130.00,
        image: "anime.jpg",
        size: ["S", "M", "L", "XL"],
        color: ["White", "Black"],
        category: "Anime",
        arrival:"New Arrival",
    },
    {
        name:"six-piece shirt",
        price: 130.00,
        image: "anime.jpg",
        size: ["S", "M", "L", "XL"],
        color: ["White", "Black"],
        category: "Motorsport",
    },
    {
        name:"seven-piece shirt",
        price: 130.00,
        image: "anime.jpg",
        size: ["S", "M", "L", "XL"],
        color: ["White", "Black"],
        category: "Motorsport",
    },
    {
        name:"eight-piece shirt",
        price: 130.00,
        image: "anime.jpg",
        size: ["S", "M", "L", "XL"],
        color: ["White", "Black"],
        category: "Motorsport",
    },
    {
        name:"nine-piece shirt",
        price: 130.00,
        image: "anime.jpg",
        size: ["S", "M", "L", "XL"],
        color: ["White", "Black"],
        category: "Motorsport",
    }
]